### ISSUE TITLE
Collides with python2-nautilus

### ISSUE THREAD

**Issue by rugk** [atenart/copr-build-mat2#1]
```sh
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction check error:
  file /usr/lib64/nautilus/extensions-3.0/libnautilus-python.so from install of python3-nautilus-1.2.2-1.fc28.x86_64 conflicts with file from package python2-nautilus-1.1-15.fc28.x86_64
```

And this is used by some other Nautilus extensions, so I cannot just remove it.

Fedora 28

---

moved from https://0xacab.org/jvoisin/mat2/issues/53

**Comment by atenart** [comment]
Thanks for reporting it, I'll have a look at this. It should be possible to rename the .so to have a unique name (otherwise I'll have to make the Python2 and Python3 versions incompatible).

**Comment by atenart** [comment]
This is now fixed in Fedora 29, as they're shipping an official python3-nautilus package.
