### ISSUE TITLE
Please verify the tarball signature

### ISSUE THREAD

**Issue by geor-g** [atenart/copr-build-mat2#3]

**Comment by rugk** [comment]
Oh yeah indeed. That's important!

**Comment by atenart** [comment]
Hi! I can only agree the tarball signature should be verified. The issue is Gitlab doesn't provide a stable URI to download uploaded files (the official tarball + sig). I also really would like to avoid downloading the sources manually for each and every new version.

**Comment by atenart** [comment]
As of 0.8.0-3, this issue is fixed.
