### ISSUE TITLE
Nautilus extension does not work on F29

### ISSUE THREAD

**Issue by rugk** [atenart/copr-build-mat2#4]
![nomenu](https://user-images.githubusercontent.com/11966684/48075232-04411500-e1e3-11e8-8d55-ebc8dbc12768.png)

This happens for other projects as well, as it seems (however, if I interpret some cases correctly, you should be fine when using `nautilus-python-3` or so, so that's strange):
* GSConnect: https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/293
* Nextcloud: https://bugzilla.redhat.com/show_bug.cgi?id=1647091

Fedora 29

**Comment by atenart** [comment]
Hi!

There currently is an issue with the python3-gobject packge in Fedora 29 which prevents the Mat2 Nautilus extension from working. A fix has been pushed into the testing repository, so it should land in f29 in some days.

**Comment by atenart** [comment]
The fix just landed, and the choice the Fedora maintainer made was to delay the python3 support until F30. This means the mat2-nautilus package is currently broken in F29, and that I'll have to provide the python3-nautilus package myself (as in F28).

I'll work on that and see what's possible. One possible issue is that nautilus-python now also provides python3-nautilus...

**Comment by atenart** [comment]
So, it turns out having python3-nautilus in copr and nautilus-python providing python3-nautilus as well doesn't work well.

**Comment by atenart** [comment]
As of 0.8.0-3 in F30, this issue is fixed.
